[workspace]
authors = ["Kim Ng <kimleeng@gmail.com>"]
channels = ["conda-forge", "bioconda", "bioconda"]
name = "ubio_autobox"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
dagster = ">=1.10.19,<2"
dagster-webserver = ">=1.10.19,<2"
duckdb = ">=1.3.0,<2"
dagster-duckdb = ">=1!0.26.19,<1!0.27"
pip = ">=25.1.1,<26"
