from ubio_autobox.projection.schema import load_atb_schema

EXPECTED = {
    "run": [
        "run_accession",
        "sample_accession",
        "in_661k",
        "in_ena_20240625",
        "in_ena_20240801",
        "in_ena_20250506",
        "ena_202505_batch",
        "fastq_md5",
        "meta_pass_atb",
        "meta_pass_661k",
        "pass",
        "comments",
    ],
    "assembly": [
        "sample_accession",
        "run_accession",
        "assembly_accession",
        "assembly_seqkit_sum",
        "asm_pipe_filter",
        "asm_fasta_on_osf",
        "dataset",
        "scientific_name",
        "sylph_species_pre_202505",
        "in_hq_pre_202505",
        "sylph_species",
        "sylph_filter",
        "hq_filter",
        "osf_tarball_filename",
        "osf_tarball_url",
        "aws_url",
        "comments",
    ],
    "assembly_stats": [
        "sample_accession",
        "total_length",
        "number",
        "mean_length",
        "longest",
        "shortest",
        "N_count",
        "Gaps",
        "N50",
        "N50n",
        "N70",
        "N70n",
        "N90",
        "N90n",
    ],
    "sylph": [
        "sample_accession",
        "run_accession",
        "Genome_file",
        "Taxonomic_abundance",
        "Sequence_abundance",
        "Adjusted_ANI",
        "Eff_cov",
        "ANI_5_95_percentile",
        "Eff_lambda",
        "Lambda_5_95_percentile",
        "Median_cov",
        "Mean_cov_geq1",
        "Containment_ind",
        "Naive_ANI",
        "Contig_name",
        "Species",
    ],
    "checkm2": [
        "sample_accession",
        "Completeness_General",
        "Contamination",
        "Completeness_Specific",
        "Completeness_Model_Used",
        "Translation_Table_Used",
        "Coding_Density",
        "Contig_N50",
        "Average_Gene_Length",
        "Genome_Size",
        "GC_Content",
        "Total_Coding_Sequences",
        "Additional_Notes",
    ],
}


def test_authoritative_column_names_and_order_are_pinned() -> None:
    schema = load_atb_schema()
    assert schema.version == "2025-05"
    assert {name: table.columns for name, table in schema.tables.items()} == EXPECTED
