FROM python:3.11-slim

WORKDIR /opt/ubio-autobox

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    DAGSTER_HOME=/opt/dagster/dagster_home

RUN apt-get update \
    && apt-get install --no-install-recommends --yes docker-cli \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml README.md LICENSE ./
COPY src ./src

RUN python -m pip install --no-cache-dir ".[local]"

ENTRYPOINT []
